---
- name: Testing andrewrothstein.jruby
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'jruby --version'
      ansible.builtin.command: bash -lc 'jruby --version'
      changed_when: false
      register: jruby_test_output
    - name: Output from 'jruby --version'
      ansible.builtin.debug:
        msg: '{{ jruby_test_output.stdout }}'
