---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/jruby/bin/jruby --version
      register: jruby_test_output
    - name: jruby --version
      debug:
        msg: '{{ jruby_test_output.stdout }}'
