---
- name: look for existing installation...
  become: yes
  become_user: root
  stat:
    path: '{{ jruby_install_dir }}'
  changed_when: False
  register: jruby_binary

- when: not jruby_binary.stat.exists
  block:
    - name: download jruby
      become: yes
      become_user: root
      get_url:
        url: '{{ jruby_url }}'
        dest: /tmp/{{ jruby_tgz }}
        checksum: '{{ jruby_checksum }}'
        mode: 0644
    - name: unarchive
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ jruby_tgz }}
        dest: '{{ jruby_install_parent_dir }}'
        creates: '{{ jruby_install_dir }}'
  always:
    - name: cleanup
      become: yes
      become_user: root
      file:
        path: /tmp/{{ jruby_tgz }}
        state: absent

- name: link
  become: yes
  become_user: root
  file:
    src: '{{ jruby_install_dir }}'
    dest: '{{ jruby_link_dir }}'
    state: link

- name: add to path
  become: yes
  become_user: root
  with_items:
    - f: jruby.sh
      d: /etc/profile.d
      m: '0644'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'
