---
- name: download jruby
  become: yes
  become_user: root
  get_url:
    url: '{{jruby_url}}'
    dest: /tmp/{{jruby_tgz}}
    checksum: '{{jruby_checksum}}'
    mode: 0644

- name: unarchive
  become: yes
  become_user: root
  unarchive:
    remote_src: yyes
    src: /tmp/{{jruby_tgz}}
    dest: '{{jruby_install_parent_dir}}'
    creates: '{{jruby_install_dir}}'

- name: link
  become: yes
  become_user: root
  file:
    src: '{{jruby_install_dir}}'
    dest: '{{jruby_link_dir}}'
    state: link

- name: add to path
  become: yes
  become_user: root
  with_items:
    - f: jruby.sh
      d: /etc/profile.d
      m: '0644'
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'
